### ISSUE TITLE
entering portal teleports me into wall

### ISSUE THREAD

**Issue by Luckyshann** [mim1q/MineCells#104]
Hi! 
I'm not sure what's happening, I've added this mod to my modpack, and when I was play testing it I've tried to enter the portal to the prisoners' quarters and when the dimension loads it just spawns me into a wall; the dungeon/dimension doesn't load at all. 
I'm not sure if I'm doing something wrong, or if it's a mod conflict, but I'm hoping someone else has encountered this!

**Comment by mim1q** [comment]
It's likely because you have [Sparse Structures](https://modrinth.com/mod/sparsestructures) installed.

Add these lines to the config file's `customSpreadFactors` array, directly blow the mansion entry:
```json
{
  "structure": "minecells:black_bridge",
  "factor": 1
},
{
  "structure": "minecells:insufferable_crypt",
  "factor": 1
},
{
  "structure": "minecells:prison",
  "factor": 1
},
{
  "structure": "minecells:promenade",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_x",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_z",
  "factor": 1
},
{
  "structure": "minecells:ramparts",
  "factor": 1
},
{
  "structure": "minecells:ramparts_second",
  "factor": 1
}
```
I have a workaround for this issue ready for the next major release, so stay tuned for that, too

**Comment by Sunconure11** [comment]
Can you verify if this is happening on other MC versions?

**Comment by mim1q** [comment]
@Sunconure11 I believe yes, the way Sparse Structures does its thing has always been incompatible with Mine Cells, unfortunately. 

**If you're playing on 1.19.2** though, this should be used in the config instead of the above.
```json
{
  "structure": "minecells:insufferable_crypt",
  "factor": 1
},
{
  "structure": "minecells:prison",
  "factor": 1
},
{
  "structure": "minecells:promenade_overground",
  "factor": 1
},
{
  "structure": "minecells:promenade_pit",
  "factor": 1
},
{
  "structure": "minecells:promenade_spawn",
  "factor": 1
},
{
  "structure": "minecells:promenade_underground",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_x",
  "factor": 1
},
{
  "structure": "minecells:promenade_wall_z",
  "factor": 1
}
```
Promenade used to be a few different structures types internally in 1.19.2, and now it's just one.

This issue *should not be happening anymore* as of Mine Cells 1.7.3 and newer, so you probably won't need to configure anything for the most recent versions of the mod
