### ISSUE TITLE
Room with a view achievement 

### ISSUE THREAD

**Issue by Aidenclink** [mim1q/MineCells#105]
I got the achievement for reaching the ramparts, but it teleported me to a random biome with prison stone, no structures or anything and I cant even explore without it teleporting me back

**Comment by mim1q** [comment]
Hey, this has happened to a few people already, so - I'm gonna need your whole modlist, or just the log file from when this happened.

I haven't figured out what's happening, yet, so you might want to teleport out of the dimension using commands (or ask an admin for help if it's a server) and not go there until the issue is fixed

**Comment by mim1q** [comment]
Should be fixed! https://modrinth.com/mod/minecells/version/1.7.3
