### ISSUE TITLE
Dying entering portal

### ISSUE THREAD

**Issue by Flnchie** [mim1q/MineCells#11]
I opened a server but everyone who enters the portal ends up "suffocating in a wall" 
I removed the mod from the pack for now but any way to solve this?

**Comment by mim1q** [comment]
Here's what the problem was - in case anyone has a similar issue in the future.
This can happen if you set a world border in your world. One way to fix that is to download [Multi World Borders](https://www.curseforge.com/minecraft/mc-mods/world-border-fix) and increase the border size  only for Mine Cells' dimension
