### ISSUE TITLE
Cursed Sword Disabled?

### ISSUE THREAD

**Issue by Koala23711** [mim1q/MineCells#121]
Hey, when I was grinding for the cursed sword and finally got all the stuff for it and hit craft. it just made a sound effect and gave me nothing. so i thought it was a glitch so i was like what ever and grinded again because the sword looked op. but then it gave me nothing again. like a whole 2 hours waisted. Is this a common glitch or is it just me? 

Also It said it was disabled when I /gave it to me in a creative test world?

How do i enable it?

Thank you,

**Comment by mim1q** [comment]
Responded on CurseForge already, but I'll send the response here too!

> Hey! You're playing Prominence II, right? The Cursed Sword is disabled there because it caused a few issues.
It's disabled through the Item Obliterator mod - but unfortunately due to a little oopsie in my code naming, the recipe didn't get disabled but the item itself did - which is why you could craft it but not actually get it. This should be taken care of with ~the next~ a future update of Item Obliterator, though!
>
> If you are aware that it might cause issues and want to re-enable the sword anyway, you can do it in the Item Obliterator `item_obliterator.json5` config file. Sorry for the problem😅
