### ISSUE TITLE
Excuse me, may I ask when the mod will be compatible with Fabric 1.21.1?

### ISSUE THREAD

**Issue by chunye-shanhui** [mim1q/MineCells#143]
Excuse me, may I ask when the mod will be compatible with Fabric 1.21.1?

**Comment by mim1q** [comment]
I'm working on a big update that'll hopefully be out late December or early January. After that I'm likely going to make a 1.21.1 version (although 1.20.1 will still be the main branch, so expect any updates to be out there sooner). This timeline might shift because I'm extremely busy with stuff outside of modding.

Closing this since it isn't really an issue, but I hope you got your answer 😃
