### ISSUE TITLE
Incompatibiliy with Create+Connectivity: Packet mixn

### ISSUE THREAD

**Issue by No3371** [mim1q/MineCells#38]
Apologize, I'd like to directly reference [another issue I raised at Connectivity's repo](https://github.com/someaddons/connectivity/issues/69).

I'm not sure about will or not and how someaddons are going to handle this compatibility issue on his end, but for my personal thought... well the first time I saw that MineCells has a mixin to modify something about packet payload, I had doubt as well, never would I expect that to be modified by a gameplay mod.

While being no judge to how this may be resolved, I decided to create this issue just to bring it to your attention 😃

**Comment by mim1q** [comment]
Hey! Yes - Mine Cells is a content-focused mod, but it also adds a few things that aren't possible by default. Hence so many mixins, so all of the mechanics work as intended 😄 

But this particular mixin was put in place because of a crash that happened in earlier versions of Mine Cells. 

The mod itself didn't actually send big packets, but when using mods that did add a lot of data to the player, the server crashed when they were entering portals. I did implement a fix in [this](https://github.com/mim1q/MineCells/blob/main/src/main/java/com/github/mim1q/minecells/mixin/network/CustomPayloadS2CPacketMixin.java) file, because mods like Connectivity and XL Packets didn't fix the crash (my solution did for some reason).

I can't resolve this issue right now, I'm quite busy for the next few weeks. Will look into it after that, but Connectivity is closed-source, so that might make things a bit more difficult 😅 Thanks for reporting!

**Comment by No3371** [comment]
Thanks for the detailed response!

**Comment by someaddons** [comment]
connectivity is visible source, so you can check out the code on github easily: https://github.com/someaddons/connectivity/tree/1.19.2forge e.g.

Issues with packet size are normally caused by bugs in mod code, causing too much data to get sent in the first place, in most circumstances you don't hit the rather high caps

**Comment by No3371** [comment]
I took a look and it seems like your mixins do target different classes (`net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket` and `net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket`)... so I guess it's possible that your implementations cover different stuff?

**Comment by someaddons** [comment]
no thats just different mappings(names) for the same thing

**Comment by No3371** [comment]
I see, apology for the misunderstanding.

Unfortunately I can not launch the server with the MineCells jar (with that mixin removed) I built because of some datapack error (`minecells:insufferable_crypt/spawn`), I can not test does MineCells work with latest Connectivity now without that mixin.

**Comment by mim1q** [comment]
@No3371 Mine Cells uses a custom python script as well as the regular datagen to generate some assets. Make sure you have Python installed, and run the `runPythonDatagen` and `runDatagen` gradle tasks :)
