### ISSUE TITLE
No Music In Conjunctivus Boss Fight and Lack of Sound

### ISSUE THREAD

**Issue by CoolPeachGaming** [mim1q/MineCells#96]
There's no music or sound effects in the Conjunctivus boss fight. I'm using The Prominence II RPG modpack and playing on a multiplayer server. Here's some lines I found in the log that might be related. It writes the missing sound for event error in the logs whenever I do things in the music and sounds menu in Minecraft, like turn on or off directional audio.
![image](https://github.com/mim1q/MineCells/assets/90976594/b43fc700-f617-44be-bbe8-c23492c5d476)
[latest.log](https://github.com/mim1q/MineCells/files/14218468/latest.log)

**Comment by mim1q** [comment]
Hey, part of this isn't a bug - there's simply no music added to Mine Cells by default due to copyright concerns. The sound events are there in case any modpack wants to add in their own music. 
These "missing sound for event" logs should actually be absent in the latest (1.6.2) release, since I added "empty" sounds to them. I made sure the next release of Prominence will have this new version :)

As for the lack of other sounds - I don't know what could be causing that, I'll try to investigate that, but it's never happened to me personally.

**Comment by CoolPeachGaming** [comment]
Ok, thank you for the quick response. Is there any way I could go about adding music to the boss fights myself?

**Comment by mim1q** [comment]
If you can make resource packs, it should be pretty simple - just make one with custom `.ogg` files for the music, and the `sounds.json` file containing the missing sound events from logs (so: `music.prisoners_quarters`, `music.promenade` etc.)
